### ISSUE TITLE
Support partial wake locks on Android 

### ISSUE THREAD

**Issue by ened** [creativecreatorormaybenot/wakelock#1]
This plugin should probably support partial wake locks (CPU only) and full wake locks (including screen) wake locks on Android.

**Comment by creativecreatorormaybenot** [comment]
@ened I will look into it. I will probably implement it, however, do you know if Flutter apps can make use of CPU wake locks?

**Comment by creativecreatorormaybenot** [comment]
@ened Do you have an example of this?  
Otherwise, I think that I might close this for now as it seems like it would add unnecessary weight to the plugin.

**Comment by ened** [comment]
Hi @creativecreatorormaybenot , sorry for the late response. More details are available here: https://developer.android.com/training/scheduling/wakelock

**Comment by creativecreatorormaybenot** [comment]
@ened Yes, I am aware of that (see #2). I mean how do you use this in a Flutter app? If you are adding native code to handle background execution anyway, it does not seem to make too much sense to add a method call to Flutter, does it?

**Comment by ened** [comment]
It is useful when running flutter isolates in the background, like in a Service object on Android for example.

**Comment by creativecreatorormaybenot** [comment]
@ened Can you link to a resource showing an implementation? I think that the android alarm manager plugin can do this, but I feel that it is not optimal to make this plugin bigger to add a feature that can only be used when installing another plugin.

**Comment by AbdulSamadgithub** [comment]
@creativecreatorormaybenot 
>@ened Can you link to a resource showing an implementation? I think that the alarm manager plugin can do this, but I feel that it is not optimal to make this plugin bigger to add a feature that can only be used when installing another plugin.

I'm running a service using this package [flutter_background_service](https://pub.dev/packages/flutter_background_service) that is executing `Timer.periodic` every second in background. After device goes to sleep and enter doze mode it stops the timer (cpu stops working). In that case having a partial wake lock is important so that service keep on working. I'll be more than happy to show you all this. 

And I'll be grateful If you'll guide me how can I implement partial wake lock. I tried and I'm getting this error 
`MissingPluginException(No implementation found for method ispartialwakelockenabled on channel`
tried : 
flutter clean, flutter pub get
double checked `invoke(string)` for any typos. 


flutter side
```
import 'package:flutter/services.dart';

class PartialWakeLock {
  static const platform = MethodChannel("keep.cpu.awake/wakelock");
  static enablePartialWakeLock() async {
    await platform.invokeMethod("enable");
  }

  static disablePartialWakeLock() async {
    await platform.invokeMethod("disable");
  }

  static isPartialWakeLockEnabled() async {
    bool result = await platform.invokeMethod('isenabled');
    return result;
  }
}
```
mainactivity
```
package com.appsync.appsync.appsync;

import android.content.ContextWrapper;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;

import android.os.PowerManager;
import android.os.PowerManager.WakeLock;

import io.flutter.embedding.android.FlutterActivity;

import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.MethodChannel;

// <--------------------imports----------------------->

public class MainActivity extends FlutterActivity {
    private static final String CHANNEL = "keep.cpu.awake/wakelock";

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);

        new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
                .setMethodCallHandler(
                        (call, result) -> {
                            // This method is invoked on the main thread.
                            PowerManager powerManager = (PowerManager) getSystemService(POWER_SERVICE);
                            WakeLock wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,
                                    "appsync::WakeLockTag");

                            if (call.method.equals("enable")) {
                                wakeLock.acquire();
                            }
                            if (call.method.equals("disable")) {
                                wakeLock.release();
                            }
                            if (call.method.equals("isenabled")) {
                                boolean isWakeLockHeld = wakeLock.isHeld();
                                result.success(isWakeLockHeld);
                            } 
                              
                        }

                );
    }
}
```

**Comment by creativecreatorormaybenot** [comment]
Hi @AbdulSamadgithub, as explained in #30 I would like to keep this plugin minimal. You can create a separate small plugin for this functionality.
