### ISSUE TITLE
Update Android project to AndroidX

### ISSUE THREAD

**Issue by shaxxx** [creativecreatorormaybenot/wakelock#10]
Google Play is now forcing developer to use new Google Play API 3.
Can you please update Android project to AndroidX.
This should be trivial using Android Studio.
More info:
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by creativecreatorormaybenot** [comment]
The project is updated to AndroidX as far as I am concerned. Can you show which parts are not?

**Comment by shaxxx** [comment]
Like I said, I was reffering to 
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
Currently points 2, 3, 4 and 5 are not implemented.

**Comment by creativecreatorormaybenot** [comment]
@shaxxx https://github.com/creativecreatorormaybenot/wakelock/commit/85bf47cb228025b6f937dccf714b25a648bcd8d9
