### ISSUE TITLE
flutter pub get not working with version 0.5.0+2

### ISSUE THREAD

**Issue by patman1706** [creativecreatorormaybenot/wakelock#106]
Hi,

i juste tried a few times to pub get the package wakelock: ^0.5.0+2
i've got the following error:

**_**The current Dart SDK version is 2.10.5.

Because myapp depends on wakelock >=0.3.0-nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
pub get failed (1; Because myapp depends on wakelock >=0.3.0-nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)
Process finished with exit code 1.**_**

i guess something must be wrong with the version check and/or null safety cause the package is supposed to require SDK version 2.12.0. it looks like beeing impossible cause i downloaded the last Dart version (2.10.5).

Could you please help me understanding the problem ?
thanks in advance.

Patrick

**Comment by patman1706** [comment]
i forgot to give this information:
SDK flutter: 1.22.6
Android Studio: 3.6.2

**Comment by creativecreatorormaybenot** [comment]
Hi @patman1706,

recently Flutter 2.0.0 was release (see https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65).

If you want to use the latest version of `wakelock`, you will have to upgrade to Flutter 2.0.0. You can do this using `flutter upgrade -f` and whatever channel you are on (the `-f` will discard any local changes to the SDK).

Hope I was able to help you 🙁

**Comment by patman1706** [comment]
Hi,

yes it worked. 

thank you.

Patrick
