### ISSUE TITLE
EXC_BAD_ACCESS when triggering wakelock on iOS

### ISSUE THREAD

**Issue by ened** [creativecreatorormaybenot/wakelock#107]
We're currently investigating a problem with this plugin when used on iOS. 
The symptom is a full app crash with EXC_BAD_ACCESS, in the iOS side's `observeValueForKeyPath` method:

<img width="1583" alt="Screenshot 2021-04-15 at 21 56 25" src="https://user-images.githubusercontent.com/269860/114937211-6df28e00-9e35-11eb-9463-abaa5f8b6ba2.png">

The stacktrace points to a recursion:
<img width="515" alt="Screenshot 2021-04-15 at 21 56 58" src="https://user-images.githubusercontent.com/269860/114937281-81055e00-9e35-11eb-8d32-14e5ed7de99e.png">

Our App actually runs two isolates, which in turn means **two** instances of the wakelock plugin are active and interfering with each other.

<img width="237" alt="Screenshot 2021-04-15 at 21 58 25" src="https://user-images.githubusercontent.com/269860/114937436-b5791a00-9e35-11eb-8cf4-2aed12cfeddd.png">

This could be resolved by setting up single observer instead of one per plugin instance.

**Comment by ened** [comment]
I have also noticed the plugin is only removing the observer in it's `dealloc` call, whereas this should probably happen in `detachFromEngineForRegistrar`:

``` objc
/**
 * Called when a plugin is being removed from a `FlutterEngine`, which is
 * usually the result of the `FlutterEngine` being deallocated.  This method
 * provides the opportunity to do necessary cleanup.
 *
 * You will only receive this method if you registered your plugin instance with
 * the `FlutterEngine` via `-[FlutterPluginRegistry publish:]`.
 *
 * @param registrar The registrar that was used to publish the plugin.
 *
 */
- (void)detachFromEngineForRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar;
```

**Comment by creativecreatorormaybenot** [comment]
@ened Sounds reasonable. I did not contribute that part of the code. Are you interested in proposing a change?

**Comment by ened** [comment]
@creativecreatorormaybenot yes, will do after #108 is merged. :)
