### ISSUE TITLE
It is not working on samsung galaxy s10 device

### ISSUE THREAD

**Issue by arunsacharyadev** [creativecreatorormaybenot/wakelock#116]

**Comment by creativecreatorormaybenot** [comment]
Hi @arunsacharyadev 👋 Thanks a lot for using the plugin and opening this issue 🙂 

Unfortunately, without any details I am not able to help you. I would assume that it works on s10 devices given the implementation, but I do not have this device myself to do any testing. Contributions are also welcome.

I can reopen the issue if you are able to provide any more details that help in potentially fixing this.
