### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by olyshchuk** [creativecreatorormaybenot/wakelock#119]
flutter:
    sdk: flutter

  **meta: ^1.2.0** to 1.3.0

  wakelock_macos: ^0.1.0+1
  wakelock_platform_interface: ^0.2.1+1
  wakelock_web: ^0.2.0+1
  wakelock_windows: ^0.1.0

**Comment by creativecreatorormaybenot** [comment]
Hi @olyshchuk, thanks for opening the issue.

What exactly is the problem you are facing?

**Comment by olyshchuk** [comment]
dart pub outdated

**Comment by creativecreatorormaybenot** [comment]
@olyshchuk I see, but this way I can ensure that old versions of Flutter are still supported 🤔 

You can force the latest meta version in your direct dependencies. However, I would say transitive outdated dependencies are acceptable, especially `meta` that is a framework dependency.

**Comment by olyshchuk** [comment]
@creativecreatorormaybenot Thanks for the answer, I will take this into account
