### ISSUE TITLE
Unable to establish connection on channel

### ISSUE THREAD

**Issue by mklepaczko** [creativecreatorormaybenot/wakelock#123]
Hi,

I'm getting this error when enabling wakelock:

/flutter ( 3917): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 3917): #0      WakelockApi.toggle
package:wakelock_platform_interface/messages.dart:57
E/flutter ( 3917): <asynchronous suspension>
E/flutter ( 3917): #1      MethodChannelWakelock.toggle
package:wakelock_platform_interface/method_channel_wakelock.dart:20
E/flutter ( 3917): <asynchronous suspension>
E/flutter ( 3917):

And it does not work. I did flutter clean but it does not help.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by creativecreatorormaybenot** [comment]
@mklepaczko Thanks for reporting the issue - which platform are you running on?

**Comment by mklepaczko** [comment]
Android

**Comment by creativecreatorormaybenot** [comment]
@mklepaczko Do you have any custom Android setup related to method channels? :)

**Comment by mklepaczko** [comment]
The only thing I changed lately was to implement FlutterFragmentActivity, perchaps this caused the issue. Here is my MainActivity.kt


`
package xxx

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}`

**Comment by mklepaczko** [comment]
To be honest I hardly know what it is apart from being used to write native code which I don't have in my app. WakeLock only works on one screen screen of my app and unfortunately I did not test that after each update so I can't remember any code change from which the bug started.

**Comment by creativecreatorormaybenot** [comment]
@mklepaczko Can you try to create a new project with a minimal reproducible sample?

**Comment by davidgtu** [comment]
I'm also receiving this error on Android. I've even added these into my `AndroidManifest`

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
....
   <activity
            android:showWhenLocked="true"
            android:turnScreenOn="true">
```

**Comment by creativecreatorormaybenot** [comment]
@davidgtu Thanks - no permission or manifest adjustments are necessary for using this plugin.

When did this error start occurring?

**Comment by mklepaczko** [comment]
Found 2 other plugins with same problem on this project, therefore the problems is outside of Wakelock. Sorry about that, thanks @creativecreatorormaybenot for your quick reply.

**Comment by mklepaczko** [comment]
Hi @creativecreatorormaybenot , after 3 days of digging and loosing time I found the problem: flutter_barcode_scanner plugin caused the problem. As soon as you put it in your dependencies it causes the problem with Wakelock and also with imagePicker, with others maybe aswell.

**Comment by creativecreatorormaybenot** [comment]
Thanks for updating me @mklepaczko 🙏 

So there is something in `flutter_barcode_scanner` that messes with the method channels? In that case, you should probably open a bug there to address this issue.

**Comment by mklepaczko** [comment]
Yes that's correct, sorry I forgot to paste the issue link: https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/217

**Comment by Universi** [comment]
Hi,

I get the same issue, but I doesn't use `flutter_barcode_scanner`.

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:89:7)
<asynchronous suspension>
#1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:20:5)
<asynchronous suspension>
```

**Comment by creativecreatorormaybenot** [comment]
@Universi can you create a reproducible sample of this without including any other dependencies?

**Comment by julianfalcionelli** [comment]
We are seeing the same in our live Apps, in the latest 30 days we got 270K exception about this:

```
PlatformException: PlatformException(channel-error, Unable to establish connection on channel., null, null)
  File "messages.dart", line 89, in WakelockApi.toggle
  File "<asynchronous suspension>"
  File "method_channel_wakelock.dart", line 20, in MethodChannelWakelock.toggle
```

<img width="1539" alt="Screen Shot 2022-12-14 at 15 07 12" src="https://user-images.githubusercontent.com/5782994/207616570-a640f42d-f698-487b-a785-0a80d786a9e7.png">

This is only happening for Android.

**Comment by gokhangg** [comment]
Hi I also have the same problem.
There are some exceptions thrown.
It happend in the file "messages.dart" at lines 89 
`
final Map<Object?, Object?>? replyMap =
     await channel.send(<Object>[arg_msg]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      **throw PlatformException(**
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    }
`

This is the code where I call wakelock:
`void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Wakelock.enable();
  runApp(MyApp());
}`
