### ISSUE TITLE
Remove JCenter from Android dependencies

### ISSUE THREAD

**Issue by grahamsmith** [creativecreatorormaybenot/wakelock#128]
With JCenter sunsetting Flutter libraries are updating away from JCenter.

Looking at the build.gradle it looks like the `google()` on its own might be sufficient. Proposal is to simply remove `jcenter()` from the build.gradle within the Android folder in the lib.

**Comment by creativecreatorormaybenot** [comment]
@grahamsmith thanks! I agree. I think it makes sense to update the plugin to match the latest templates :)

**Comment by grahamsmith** [comment]
It's a super useful package, one of the first I used. Thanks for taking the time.

I'll handle Jcenter if you want as it's good to give back.
