### ISSUE TITLE
Debug causes assertion fail in Linux (when not using)

### ISSUE THREAD

**Issue by bksubhuti** [creativecreatorormaybenot/wakelock#132]
Summary:  Linux is not supported.  However, conditions cannot be made that "skips over" wakelock code if the package is included.

Please see this issue here:
https://github.com/Baseflow/flutter-geolocator/issues/818

I commented out the code falls on (dispose) and still problems.  Therefore there is no code being called.
It seems that importing the package header will cause a debug assert at the close of the widget (page).

There are no flutter supports for conditional imports.

**Comment by creativecreatorormaybenot** [comment]
Hi @bksubhuti, the plugin is indeed not supported on Linux.

You have two options:
1. Contribute Linux support

2. Do not call wakelock code on Linux (`kIsWeb || !Platform.isLinux`).

**Comment by creativecreatorormaybenot** [comment]
Closing as duplicate of #97.
