### ISSUE TITLE
classpath version 1.3, which is older than the API version 1.5

### ISSUE THREAD

**Issue by stephane-couget** [creativecreatorormaybenot/wakelock#135]
Hello everybody,

Since this morning, it seems that I have to use kotlin in its version 1.5.30 instead of 1.5.21, according to gradle who returns me this:

`[        ] > Task :wakelock:generateDebugBuildConfig UP-TO-DATE
[+1163 ms] > Task :wakelock:compileDebugKotlin FAILED
[   +1 ms] w: Runtime JAR files in the classpath have the version 1.3, which is older than the API version 1.5. Consider using the runtime of version 1.5, or pass '-api-version 1.3' explicitly to restrict the available APIs to the runtime of version 1.3. You can also pass '-language-version 1.3' instead, which will restrict not only the APIs to the specified version, but also the language features`

`[        ] w: /Users/userName/.gradle/caches/transforms-2/files-2.1/52af8cf5caf1156de1a0dca4f85161fc/jetified-kotlin-stdlib-common-1.3.50.jar: Runtime JAR file has version 1.3 which is older than required for API version 1.5
[        ] w: /Users/userName/.gradle/caches/transforms-2/files-2.1/725f7f054bb8714e5b7cc92bdd60f5ce/jetified-kotlin-stdlib-1.3.50.jar: Runtime JAR file has version 1.3 which is older than required for API version 1.5
[        ] w: /Users/userName/.gradle/caches/transforms-2/files-2.1/e32f9dede052a4391cef1ec7fd2cbe85/jetified-kotlin-stdlib-jdk7-1.3.50.jar: Runtime JAR file has version 1.3 which is older than required for API version 1.5
[   +4 ms] e: /Users/userName/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.3+3/android/src/main/kotlin/creativemaybeno/wakelock/WakelockPlugin.kt: (13, 25): Unresolved reference: Wakelock
[  +24 ms] e: /Users/userName/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.3+3/android/src/main/kotlin/creativemaybeno/wakelock/WakelockPlugin.kt: (17, 16): Unresolved reference: Wakelock
[        ] e: /Users/userName/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.3+3/android/src/main/kotlin/creativemaybeno/wakelock/WakelockPlugin.kt: (26, 15): Variable expected
[        ] e: /Users/userName/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.3+3/android/src/main/kotlin/creativemaybeno/wakelock/WakelockPlugin.kt: (30, 15): Variable expected
[+1002 ms] > Task :app:processDebugResources
[ +199 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':wakelock:compileDebugKotlin'.`

In Android Studio, do you have a way to customize classpath just for your plugin, or do I have to wait until you go up to your wakelock classpath plugin in version 1.5?

Thank you all for your efforts, see you soon,

**Comment by creativecreatorormaybenot** [comment]
Hi @stephane-couget :) Why do you have to use the newer version?

**Comment by stephane-couget** [comment]
The twenty or so other plugins I use require 1.5 according to gradle so I had to downgrade from 1.3 to 1.5. I am the wave to pass the debugging compilation.
All summer I was faced with this kind of problem, for practically all the plugins, some took advantage of the transition to null safe to do so. But maybe it's not useful, that we could customize by plugin. But I do not know how.

Not all plugins are just dart, there are pieces of java and kotlin. I try to avoid them as much as possible. The important thing is that I can continue my compilations in order to advance in my project.

**Comment by creativecreatorormaybenot** [comment]
@stephane-couget I am pretty sure `wakelock` just uses the official Flutter plugin template, so it should be the same as all the other plugins. Can you point me to where in the code this is?

**Comment by creativecreatorormaybenot** [comment]
Will close this for now since there is no issue to my knowledge.
