### ISSUE TITLE
0.5.4 - crashes on launch on iOS

### ISSUE THREAD

**Issue by PerLycke** [creativecreatorormaybenot/wakelock#140]
Previous versions worked fine but 0.5.4 crashes on launch on iOS with the following error shown in Xcode:

> Exception	NSException *	"FLTWakelockApi api doesn't respond to @selector(toggleMsg:error:)"	0x00000002813c23a0

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/per/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0
```

**Comment by doubletcjs** [comment]
+1

**Comment by creativecreatorormaybenot** [comment]
Please use:

```
wakelock: 0.5.3+3
```

For the moment.

**Comment by jinliyuelong** [comment]
+1

**Comment by gilescm** [comment]
I've just experienced this issue on `0.5.3+3` I've also tried `0.5.3` and `0.5.2` and no luck (didn't try +2 and +1 of 0.5.3 since the changelog only references android changes)

iOS Version 14.7.1

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/giles/Library/flutter
    • Framework revision 02c026b03c (4 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1
```

**Comment by creativecreatorormaybenot** [comment]
@gilescm That is not possible - version `0.5.3+3` did not have this assertion yet (see https://github.com/flutter/flutter/issues/89838). You might need to clean the cache in that case.

Note that you need to **specifically** point to `wakelock: 0.5.3+3` (**without** the caret `^`). And then run `pub get` again.

**Comment by jinliyuelong** [comment]
Please release a version as soon as possible, because I use chewie1.2.2, it is using ^0.5.2, I do not want to use dependency_overrides to solve, need to change the corresponding library, too much

**Comment by stuartmorgan** [comment]
https://github.com/creativecreatorormaybenot/wakelock/blob/main/wakelock/ios/Classes/WakelockPlugin.m#L20
And
https://github.com/creativecreatorormaybenot/wakelock/blob/main/wakelock/ios/Classes/WakelockPlugin.m#L30
Need to be updated so that the signatures match the new version of the generated protocol:
https://github.com/creativecreatorormaybenot/wakelock/blob/main/wakelock/ios/Classes/messages.h#L26-L27

**Comment by gilescm** [comment]
@creativecreatorormaybenot That worked thanks! Sorry I should've realised! 😓

**Comment by creativecreatorormaybenot** [comment]
@jinliyuelong 

> Please release a version as soon as possible, because I use chewie1.2.2, it is using ^0.5.2, I do not want to use dependency_overrides to solve, need to change the corresponding library, too much

You can do it like this for the moment:

```yml
dependencies:
  chewie: ^1.2.2
  wakelock: 0.5.3+3
```

**Comment by creativecreatorormaybenot** [comment]
(but I am working on fixing this - thanks @stuartmorgan)

**Comment by darmie** [comment]
@creativecreatorormaybenot how do I clear cache? I have tried `flutter clean` and deleted pod files and build folders manually
>That is not possible - version 0.5.3+3 did not have this assertion yet (see flutter/flutter#89838). You might need to clean the cache in that case.

**Comment by creativecreatorormaybenot** [comment]
@darmie Just use exactly this:

```yml
  wakelock: 0.5.3+3
```
**without** a caret `^` and run `pub get` :v:

**Comment by darmie** [comment]
@creativecreatorormaybenot I was just about to delete the comment, the new culprit is firebase. Thanks for the quick response.

**Comment by kirimi** [comment]
With wakelock: **0.5.3+3** and  flutter **2.5.0**  crashes with 

*** Assertion failure in -[FlutterStandardReader readValueOfType:], FlutterStandardCodec.mm:474
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Corrupted standard message'

**Comment by rickcasson** [comment]
In addition to specifying 
```
dependencies:
  ...
  wakelock: 0.5.3+3
```

we also added
```
dev_dependencies:
  ...
  wakelock_platform_interface: 0.2.1+2
```

and it seems to work on our iOS builds again

**Comment by scroft13** [comment]
> In addition to specifying
> 
> ```
> dependencies:
>   ...
>   wakelock: 0.5.3+3
> ```
> 
> we also added
> 
> ```
> dev_dependencies:
>   ...
>   wakelock_platform_interface: 0.2.1+2
> ```
> 
> and it seems to work on our iOS builds again

This last line saved me. It was causing issues with my video calling dependency. I was banging my head against the wall trying to figure out why my video calling wasn't working now. Adding the first line fixed the initial crash, but adding the second line resolved my other issues. 

A truly heart-felt thank you good sir!

**Comment by stuartmorgan** [comment]
> *** Assertion failure in -[FlutterStandardReader readValueOfType:], FlutterStandardCodec.mm:474
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Corrupted standard message'

This error is because Pigeon 1.0 uses a different codec (as noted in the changelog), which means that with the method channel in a different package from the native implementations using it, updating Pigeon in the platform interface was actually a breaking change. Having one side of a platform channel using Pigeon 0.2 and the other side using Pigeon 1.0 will not work at all.

Because the `wakelock_platform_interface` version wasn't changed to indicate that, but is instead incorrectly marked as a bugfix release, pub will allow resolving incompatible versions.

**Comment by smyer** [comment]
> In addition to specifying
> 
> ```
> dependencies:
>   ...
>   wakelock: 0.5.3+3
> ```
> 
> we also added
> 
> ```
> dev_dependencies:
>   ...
>   wakelock_platform_interface: 0.2.1+2
> ```
> 
> and it seems to work on our iOS builds again

In two days we have a live premiere in theater with 80 Persons and the app suddenly doesnt work anymore. After 5 hours of being absolutely helpless, YOU SAVED MY LIVE!!!

1000 thanks

**Comment by lekhanhtoan37** [comment]
Flutter 2.0.2, wakelock: 0.5.2
I met the same crash

**Comment by Mocaris** [comment]
Me too, but it works on 0.5.3+3

**Comment by vlowe85** [comment]
im on 0.5.3+3 and it launches ok, but it crashes as soon as i call `Wakelock.enable()` or `Wakelock.disable()`

**Comment by vlowe85** [comment]
> With wakelock: **0.5.3+3** and flutter **2.5.0** crashes with
> 
> *** Assertion failure in -[FlutterStandardReader readValueOfType:], FlutterStandardCodec.mm:474
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Corrupted standard message'

same

**Comment by kirimi** [comment]
> > With wakelock: **0.5.3+3** and flutter **2.5.0** crashes with
> > *** Assertion failure in -[FlutterStandardReader readValueOfType:], FlutterStandardCodec.mm:474
> > *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Corrupted standard message'
> 
> same

This combination works:

dependencies:
  wakelock: 0.5.3+3
dev_dependencies:
  wakelock_platform_interface: 0.2.1+2

**Comment by creativecreatorormaybenot** [comment]
**@everyone**: this should be fixed in `wakelock: 0.5.5` 🚀🤘

Let me know if it works again for you - and sorry for this, 1000 ❤️

**Comment by hsandyque** [comment]
@creativecreatorormaybenot  pub get failed  " on wakelock 0.5.6 which doesn't match any versions, version solving failed."
pub get failed

**Comment by creativecreatorormaybenot** [comment]
@hsandyque give it 5min, CD is still publishing `0.5.6` 🚀 I will repost the other comment, so that it is at the bottom :v:

**Comment by creativecreatorormaybenot** [comment]
**@everyone**: this should be fixed in `wakelock: 0.5.6` 🚀🤘

Let me know if it works again for you - and sorry for this, 1000 ❤️  
This definitely cannot happen again.

**Comment by nohli** [comment]
@creativecreatorormaybenot 0.5.6 works for me 🙂
Thanks for the fix! ❤️

**Comment by mathiuleo** [comment]
@creativecreatorormaybenot Thank you. Much appreciated.
