### ISSUE TITLE
Wakelock 0.5.4 might not work on Android?

### ISSUE THREAD

**Issue by MrCsabaToth** [creativecreatorormaybenot/wakelock#141]
I recently upgraded to Flutter 2.5 stable. I use Wakelock only on a specific screen of my app where it is necessary. At the beginning of `initState` I call `Wakelock.enable()` (without await since the `initState` is not async) and in `dispose` (which is similarly not async) I call `Wakelock.disable()`. This worked beofre but for some reaosn it does not work now and the phone (OnePlus Nord, Android 11) goes to sleep like a baby. Not sure if it was definitely the 2.5 Flutter update since I'm dealing with code churn, but I don't know what else. I wonder if anyone else has this problem.

**Comment by bailyzheng** [comment]
I got the same problem

**Comment by MrCsabaToth** [comment]
> I got the same problem

Thanks for the feedback, so I'm not the only one. What phone, what Android version. I wonder if it is specific to certain versions or some criteria otherwise people would be more vocal (I assume). Are you also using the lock on a specific screen or throughout the whole app? Wakelock not working basically makes the package useless.

**Comment by creativecreatorormaybenot** [comment]
hi @MrCsabaToth - thanks a lot for opening the issue!

What version of wakelock are you using? (either the `pubspec.lock` entry or `flutter pub deps` works)

I might have screwed up `wakelock: 0.5.4` on Android in the same way I screwed it up on iOS (see #140). I will definitely address the other issue, but I am not sure if this is related.

I can definitely confirm that `0.5.3` is working on Android (we are using it in production apps).

**Comment by MrCsabaToth** [comment]
I upgraded to 0.5.4 recently. Time to time I do a "Pub outdated" and update my pubspec.yaml because I have every package pinned. I haven't really debugged into this issue, let me know how can I help, what can I watch out for.

**Comment by creativecreatorormaybenot** [comment]
@MrCsabaToth If you use `0.5.6`, I am confident it works. The only way to move forward here would be to identify particular devices / Android versions where it does not work and a reproducible sample.

The general advice I give is: calling `Wakelock.enable()` more often is safe, i.e. it might be the wakelock is released somehow and if you reactivate it at every point you know it should be active, that can be a fix.

**Comment by MrCsabaToth** [comment]
I see 0.5.6 is a recent release. I'll try to test it soon

**Comment by MrCsabaToth** [comment]
Good news: I tested 0.5.6 and the wakelock works with that version! I wonder if @bailyzheng has the same experience.

**Comment by creativecreatorormaybenot** [comment]
Thanks @MrCsabaToth 👌 

I will close this issue for now - @bailyzheng feel free to ping me if you are experiencing the issue still.
