### ISSUE TITLE
ANR Broadcast of Intent { act=android.intent.action.SCREEN_OFF flg=0x50200010 (has extras) }

### ISSUE THREAD

**Issue by victorkifer** [creativecreatorormaybenot/wakelock#151]
After adding wakelock in one of the screens in my app I started seeing ANR reports in Play Console.

```
Broadcast of Intent { act=android.intent.action.SCREEN_OFF flg=0x50200010 (has extras) }
```

It doesn't seem to be specific to any particular model or manufacturer. However, all the reports I got are from Android 10. My target SDK is 30.

It might be related to https://stackoverflow.com/a/63956354

**Comment by creativecreatorormaybenot** [comment]
I will close this for now as this does not seem to be reproducible. If you have more information, I will be glad to reopen the issue :v:
