### ISSUE TITLE
Infinite loop ,crashed on iOS

### ISSUE THREAD

**Issue by suyaolingoace** [creativecreatorormaybenot/wakelock#155]
If someone change 'UIApplication.sharedApplication.idleTimerDisabled = YES', the wakelock will crash.

First, wakelock had add **Observer** at registerWithRegistrar:
![Screen Shot 2021-12-14 at 10 45 01 AM](https://user-images.githubusercontent.com/88423647/145924376-b30b77cf-90b0-4d11-89d5-cfb61fa9f8bb.png)

Then, if some set 'UIApplication.sharedApplication.idleTimerDisabled = YES' and self.enable = NO, will cause infinite loop.

![Screen Shot 2021-12-14 at 10 46 02 AM](https://user-images.githubusercontent.com/88423647/145924511-3edcd2ab-8e1e-484c-8cdd-8df1a61ea84a.png)

So, Do Not use setter method in his KVO, and exposure method to **remove** the observer

**Comment by creativecreatorormaybenot** [comment]
Hi, thanks for reporing this issue! This seems related to #154 - do you know what causes this? Would you be able to contribute a fix?

**Comment by suyaolingoace** [comment]
Have fixed at PR  [#156](https://github.com/creativecreatorormaybenot/wakelock/pull/156#issue-1083181050)
