### ISSUE TITLE
Wakelock cannot be enabled programmatically on mobile browsers

### ISSUE THREAD

**Issue by L0LIC0N** [creativecreatorormaybenot/wakelock#158]
#### Describe the bug
I want to enable wakelock only for specific page of my app. To achieve this, I call `Wakelock.enable()` in the `initState` and `Wakelock.disable()` in `dispose`. It seems to work perfectly fine on android and iOS versions and Web PC too. But on mobile browsers (ie chrome on Android and Safari on iOS) it  doesn't work, it throw me an `NotAllowedError`. Since the `wakelock_web` package use `NoSleep.js` which basically play a video to avoid the screen to turn off, it can't be used without a user-gesture.

### Steps to Reproduce
```dart
import 'package:flutter/material.dart';
import 'package:wakelock/wakelock.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        backgroundColor: Colors.grey[300],
        primarySwatch: Colors.blue,
      ),
      home: const WakelockTest(),
    );
  }
}

class WakelockTest extends StatefulWidget {
  const WakelockTest({ Key? key }) : super(key: key);

  @override
  _WakelockTestState createState() => _WakelockTestState();
}

class _WakelockTestState extends State<WakelockTest> {

  @override
  void initState() {
    Wakelock.enable();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Wakelock.enabled,
      builder: (context, snapshot) {
        if (snapshot.hasError){
          return Center(child: Text(snapshot.error.toString(), style: const TextStyle(color: Colors.red)));
        }else if (snapshot.connectionState != ConnectionState.done){
          return Container();
        }else{
          return FittedBox(child: Padding(padding: const EdgeInsets.all(20),
            child:  GestureDetector(
              child: Icon(Icons.lightbulb_outline, color: snapshot.data ==true ? Colors.yellow : Colors.black),
              onTap: () => setState(() {
                Wakelock.toggle(enable: !(snapshot.data == true));
              })
            )
          ));
        }
      }
    );
  }

  @override
  void dispose() {
    Wakelock.disable();
    super.dispose();
  }
}

```
And run `flutter build web --profile --dart-define=Dart2jsOptimization=O0` for debug purposes.

### More informations
Tested on chrome with an ASUS_X00PD with Android 8.0.0 and on Safari with an Iphone 7 with iOS 14.8

**Edit :** It works on android with chrome version 84+ since `wakelock_web` supports the [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API)

**Comment by creativecreatorormaybenot** [comment]
Hi - this is not really a limitation of the plugin but rather a security limitation of web browsers. As you stated, if the[ Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) is available, this is not an issue.
