### ISSUE TITLE
MissingPluginException(No implementation found for method toggle on channel wakelock)

### ISSUE THREAD

**Issue by MichaelHipp** [creativecreatorormaybenot/wakelock#16]
I'm getting the exception & stack trace shown below. I've tried putting the call in a couple of different places.

```
import 'package:wakelock/wakelock.dart';
...
Wakelock.enable();
```

```
E/flutter ( 9671): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method toggle on channel wakelock)
E/flutter ( 9671): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 9671): <asynchronous suspension>
E/flutter ( 9671): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 9671): #2      Wakelock.enable (package:wakelock/wakelock.dart:21:16)
```

Any suggestions?

**Comment by MichaelHipp** [comment]
Well evidently this is a common problem with Flutter and likely has nothing to do with this plugin. I solved it by stopping the debugger, doing 'flutter clean' in the terminal and restarting the app.

Found some discussion of it in this thread: https://github.com/flutter/flutter/issues/10912#issuecomment-310637961 . That's where the idea of doing flutter clean came from.

**Comment by creativecreatorormaybenot** [comment]
@MichaelHipp Did you run on Android or iOS or another platform? There are definitely implementation for those two, but web and desktop does not have implementationa.
