### ISSUE TITLE
`Wakelock.enable()` does not work on Android

### ISSUE THREAD

**Issue by rohitvishwakarma1819** [creativecreatorormaybenot/wakelock#160]
I just created a bank flutter application and added 
`  Wakelock.enable();` as the first line inside main() method.
I doesn't prevent my app from going to sleep.

**Comment by creativecreatorormaybenot** [comment]
Hi, thanks for using the package! Without further detail, it will be impossible to help you here. The package does work for most users after all.

Which phone are you using?

**Comment by rohitvishwakarma1819** [comment]
@creativecreatorormaybenot I'm using moto G40 fusion (arm-64) with Anfroid-11

**Comment by creativecreatorormaybenot** [comment]
@rohitvishwakarma1819 I do not have this device here to test. Can you test on a different device and confirm that the wakelock is working, i.e. that you are using it properly?

**Comment by itssidhere** [comment]
Same. Doesn't work with Android 11

**Comment by creativecreatorormaybenot** [comment]
@itssidhere hi - thanks for reporting. I have the same request for you, i.e. sharing how you are using it / testing with different devices for reproduction :v:

**Comment by itssidhere** [comment]
@creativecreatorormaybenot seems like it's the issue with latest flutter version 2.9 can't be sure though I am using poco X3 Pro and yes it doesn't work on any of my devices

**Comment by creativecreatorormaybenot** [comment]
@itssidhere I checked again on my devices and I cannot reproduce.

Without further input, I cannot help you here - unfortuantely. You will at least have to either debug the issue yourself and figure out where it comes from or post a reproducible sample. My advice would be to use the example app for testing this.

**Comment by paj-co** [comment]
I have tested wakelock on Samsung A21s with Android 11. I'm using Flutter 2.8.1 stable, everything is working fine 👍

**Comment by itssidhere** [comment]
@creativecreatorormaybenot I agree I might have to look in detail. I will do so and update you. Thanks.

**Comment by scognito** [comment]
Doens't work on my Android 11 Xiaomi 10 lite 5g.
Flutter version 2.8.1
Available for testing if you tell me how to do.

**Comment by BunnyTheLifeguard** [comment]
Same here, using a Moto G7 Plus, tho with Lineage OS 18.1 which is based on Android 11.

```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (5 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

Also, just to make sure I did not use it incorrectly? 😅
```dart
import 'package:flutter/material.dart';
import 'package:wakelock/wakelock.dart';

void main() {
  Wakelock.enable();

  runApp(MaterialApp(
    initialRoute: '/home',
    routes: {
      ...
    },
  ));
}
```

**Comment by creativecreatorormaybenot** [comment]
@BunnyTheLifeguard Can you try calling `Wakelock.enable` more often? As in make sure that it is not released during the app lifecycle?
You could even call it in `build` if you wanted to

**Comment by BunnyTheLifeguard** [comment]
@creativecreatorormaybenot looks like calling it inside a build took care of it, device did not go to sleep so far.

```dart
@override
  Widget build(BuildContext context) {
    Wakelock.enable();

    return const Scaffold(
      body: Text("loading"),
    );
  }
```

Where would the most central/earliest opportunity be to call it, or does one have to call it inside every build? (Still learning the framework ^^)

**Comment by creativecreatorormaybenot** [comment]
@BunnyTheLifeguard Calling it inside of `build` is mostly arbitrary. What I think might be the case is that either you are calling `Wakelock.disable()` somewhere or the wakelock is released by another source.

A third option that I see is the following:

```dart
void main() {
  Wakelock.enable();

  runApp(..);
}
```

**Will not work**. That is because the method channels have not yet been initialized.  
You either have to call it **after** `runApp` or initialize the widgets binding beforehand:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Wakelock.enable();

  runApp(..);
}
```

**Comment by BunnyTheLifeguard** [comment]
@creativecreatorormaybenot Thanks for explaining, brother 🙂
Intersting, I have to read more about the `WidgetsFlutterBinding.ensureInitialized();` 👀

Just as an fyi: I did not call anything besides `Wakelock.enable();` so you can rule out option 1. WL being released by another source I can't tell since I'm not experienced enough overall with flutter yet. I was using it during/in a simple tutorial project, so nothing too complex. Hope that helps.

**Comment by pdivita** [comment]
Worked for me, I suggest to add in the README.
BTW I'm using version 0.5.6 because of this [issue](https://github.com/creativecreatorormaybenot/wakelock/issues/167).

> @BunnyTheLifeguard Calling it inside of `build` is mostly arbitrary. What I think might be the case is that either you are calling `Wakelock.disable()` somewhere or the wakelock is released by another source.
> 
> A third option that I see is the following:
> 
> ```dart
> void main() {
>   Wakelock.enable();
> 
>   runApp(..);
> }
> ```
> 
> **Will not work**. That is because the method channels have not yet been initialized. You either have to call it **after** `runApp` or initialize the widgets binding beforehand:
> 
> ```dart
> void main() {
>   WidgetsFlutterBinding.ensureInitialized();
>   Wakelock.enable();
> 
>   runApp(..);
> }
> ```

**Comment by creativecreatorormaybenot** [comment]
> Worked for me, I suggest to add in the README.

That is great to hear @pdivita! Which fix are you referring to?

**Comment by BunnyTheLifeguard** [comment]
In my case in a new project both worked.
Tho I had to upgrade Kotlin version in build.gradle, since it is only created with 1.3.50.

**Comment by pdivita** [comment]
> > Worked for me, I suggest to add in the README.
> 
> That is great to hear @pdivita! Which fix are you referring to?

Wakelock started working after I've added `WidgetsFlutterBinding.ensureInitialized();` before the call.
