### ISSUE TITLE
wrong Kotlin version?

### ISSUE THREAD

**Issue by fehernyul** [creativecreatorormaybenot/wakelock#169]
\.pub-cache\hosted\pub.dartlang.org\wakelock-0.6.1]()+1\android\src\main\kotlin\creativemaybeno\wakelock\Wakelock.kt: (23, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is **1.5.1**, expected version is **1.1.15.**

**Comment by creativecreatorormaybenot** [comment]
Duplicate of #162
