### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [creativecreatorormaybenot/wakelock#17]
Web support should be added as soon as *wakelock* functionality is available for the web.

It is currently only an experimental feature, see https://web.dev/wakelock/.

The w3c specification can be found [here](https://w3c.github.io/wake-lock/).

**Comment by aafanasev** [comment]
If someone impatient like me, there is a workaround. I forked this repo and added web support which calling JS code in your index.html. On HTML side I used a tricky NoSleep library which adds `video` tag and plays or pauses the empty video, this is how it prevents sleep 😄 

Fork: https://github.com/aafanasev/wakelock 
NoSleep: https://github.com/richtr/NoSleep.js
Sample index.html: https://github.com/aafanasev/scrum-poker/blob/3cf9e093598a9a6b88f7fd77a0dbdda43784dd6a/web/index.html

**Comment by creativecreatorormaybenot** [comment]
@aafanasev Looks interesting. If you want to open a pull request, go ahead and do so. I would look a bit more into NoSleep then. 

Not sure if it is the best idea to add this workaround to the plugin, but we could deal with that then. It would require adding to the README etc.

**Comment by aafanasev** [comment]
I don't think it's the best idea either. The number of "Not working" issues of NoSleep scaring me. I just wanted to show there is a possibility for whoever comes to this issue.

Carefully look into the solution and if you're strongly sure I don't mind creating PR.

**Comment by IchordeDionysos** [comment]
Chrome recently released the Wake Lock API to stable:

https://caniuse.com/#feat=wake-lock

It's in there since Chrome 85 (released on August 25th, 2020)
