### ISSUE TITLE
win32 ^2.0.0, version solving failed

### ISSUE THREAD

**Issue by LinHaoLove** [creativecreatorormaybenot/wakelock#180]
Hi,Sir,
Good morning，
In my project, I use both ”wakelock“ and "bitsdojo_window". This operation will cause "win32" library dependency conflicts. I use to change the version number to "any", which can solve the conflict. But the dependent version is a little old. So, thank you very much for inviting you to upgrade the plug-in dependency.

**Comment by LinHaoLove** [comment]
Mac OS 12.5.1 （Mac mini m1）
Flutter SDK arm64 3.3.0

**Comment by creativecreatorormaybenot** [comment]
Hi, thanks for opening the issue! Do you mind opening a PR to bump the version?

**Comment by LinHaoLove** [comment]
oh,I still have a lot of bad tasks to complete.
but i will leave a message when I find a problem.
