### ISSUE TITLE
iOS build issue when changing to flutter 3.3.0

### ISSUE THREAD

**Issue by itamardo** [creativecreatorormaybenot/wakelock#181]
Hi.
I'm use codemagic to build for iOS and when using flutter 3.3.0 I get the following error:
```[!] CocoaPods could not find compatible versions for pod "Flutter":
      In Podfile:
        Flutter (from 'Flutter')

        wakelock (from '.symlinks/plugins/wakelock/ios') was resolved to 0.0.1, which depends on
          Flutter

    Specs satisfying the 'Flutter (from 'Flutter'), Flutter' dependency were found, but they required a higher minimum deployment target.
```

**Comment by creativecreatorormaybenot** [comment]
Hi, thanks for opening the issue. Do you mind opening a PR to bump the dependency?

**Comment by itamardo** [comment]
Sure. Followed the guidelines here about opening a PR and changed only the pubspec and the changelog. Hope it's what you meant

**Comment by creativecreatorormaybenot** [comment]
I realized I commented on a different issue than I thought. After having read through your logs again now, I am not sure what causes the issue exactly.

It looks like the minimum deployment target of your iOS app is too low. In that case, no change of the plugin would be required and instead you need to adjust that in your app.

**Comment by itamardo** [comment]
ok, thanks
what should that new minimum be?

**Comment by itamardo** [comment]
update: apparently 11 is enough
