### ISSUE TITLE
 migrated to the Android embedding v2

### ISSUE THREAD

**Issue by mohamedMesalm** [creativecreatorormaybenot/wakelock#184]
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `wakelock` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

**Comment by creativecreatorormaybenot** [comment]
Hi, thanks for reporting the issue. If you read the error message carefully, your app has to be migrated to the new embedding and not the plugin.

Simply follow the guides referred to in the error message.
