### ISSUE TITLE
Wakelock ineffective when calling back app after suspend

### ISSUE THREAD

**Issue by mfizz1** [creativecreatorormaybenot/wakelock#193]
I believe this is known as onsuspend / onresume / onoause etc, when the user presses the home button. Then when the user puts the app back in view the screensaver is visible again after system elapsed time.

Is there a preferred way of tackling this?

**Comment by creativecreatorormaybenot** [comment]
Please use [`didChangeAppLifecycleState`](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html) to activate the wakelock again.

**Comment by mfizz1** [comment]
Thanks for the response, this was what I was planning on doing, however, when testing through this, not sure if this is a bug or intended purpose

I called this function and checked `Wakelock.enabled` and it comes back as `true` on both states `paused` and `resumed` Is it incorrectly stating this and `Wakelock.enable()` should be called regardless on resumed?

**Comment by creativecreatorormaybenot** [comment]
@mfizz1 If `Wakelock.enabled` still returns `true`, the wakelock should still be enabled, since the plugin checks the **native** flag to retrieve the `Wakelock.enabled` state.
