### ISSUE TITLE
win32 ^3.0.0 - version mismatch

### ISSUE THREAD

**Issue by fikretonuresen** [creativecreatorormaybenot/wakelock#194]
I need to upgrade file_picker to fix a bug but this version mismatch is not allowing me.
I'm gonna make a pull request about this too.

In short win32 needs to be upgraded to ^4.1.3

`Because no versions of wakelock_windows match >0.2.1 <0.3.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
And because wakelock_windows 0.2.1 depends on win32 ^3.0.0 and file_picker >=5.2.11 depends on win32 ^4.1.3, file_picker >=5.2.11 is incompatible with wakelock_windows <0.3.0.
And because wakelock 0.6.2 depends on wakelock_windows ^0.2.0 and no versions of wakelock match >0.6.2 <0.7.0, file_picker >=5.2.11 is incompatible with wakelock ^0.6.2.
So, because routewix_executive depends on both wakelock ^0.6.2 and file_picker ^5.2.11, version solving failed.`

**Comment by MrCsabaToth** [comment]
File picker here as well:
`And because file_picker >=5.2.11 depends on win32 ^4.1.3, wakelock ^0.6.2 is incompatible with file_picker >=5.2.11.`

Thanks for your PR

**Comment by dzab5** [comment]
im getting fatal: repository 'https://github.com/timsneath/wakelock/' not found when trying this

> I recommend overriding `wakelock_windows`:
> 
> ```yaml
> dependency_overrides:
>   # Can be removed when
>   # https://github.com/creativecreatorormaybenot/wakelock/pull/203 is merged.
>   wakelock_windows:
>     git:
>       url: https://github.com/timsneath/wakelock
>       ref: win32-v5
>       path: wakelock_windows
> ```

**Comment by nilsreichardt** [comment]
@dzab5 I updated the comment with a different repository which works 👍

**Comment by creativecreatorormaybenot** [comment]
I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
