### ISSUE TITLE
Need update on dependencies as other important dependencies updated their versions

### ISSUE THREAD

**Issue by imijanur** [creativecreatorormaybenot/wakelock#207]
After dart 3.10 dependencies are being upgraded and its being incompatible with others. I have chewie player and razorpay payment getway in my project. chewie player has dependency of wakelock which depends on windows_wakelock wich depends on win32 dependency version ^3.0.0

But razorpay depends on package_info_plus which depends on win32 version ^4.0.0 so i am unable to run my project properly, please update with compitable version

here is the log bellow for details

`
Resolving dependencies...
Because no versions of wakelock_windows match >0.2.0 <0.2.1 and wakelock_windows >=0.2.1 depends on win32 ^3.0.0, wakelock_windows >0.2.0 requires win32 ^3.0.0.
And because wakelock_windows 0.2.0 depends on win32 ^2.0.0, wakelock_windows >=0.2.0 requires win32 ^2.0.0 or ^3.0.0.
Because razorpay_flutter >=1.3.5 depends on package_info_plus ^4.0.1 which depends on win32 >=4.0.0 <6.0.0, razorpay_flutter >=1.3.5 requires win32 >=4.0.0 <6.0.0.
Thus, razorpay_flutter >=1.3.5 is incompatible with wakelock_windows >=0.2.0.
And because wakelock 0.6.2 depends on wakelock_windows ^0.2.0, razorpay_flutter >=1.3.5 is incompatible with wakelock 0.6.2.
Because chewie >=1.3.5 depends on wakelock ^0.6.2 and no versions of wakelock match >0.6.2 <0.7.0, chewie >=1.3.5 requires wakelock 0.6.2.
Thus, razorpay_flutter >=1.3.5 is incompatible with chewie >=1.3.5.
So, because bt_universal depends on both chewie ^1.5.0 and razorpay_flutter ^1.3.5, version solving failed.
`

**Comment by giovanni256** [comment]
Same here

**Comment by sarankumar-ns** [comment]
+1

**Comment by madatr** [comment]
+1

**Comment by utrayn** [comment]
+1

**Comment by jamesncl** [comment]
This package appears to be abandoned, so a community fork has been created: [https://pub.dev/packages/wakelock_plus](https://pub.dev/packages/wakelock_plus)

**Comment by creativecreatorormaybenot** [comment]
I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
