### ISSUE TITLE
State of wakelock package

### ISSUE THREAD

**Issue by ImClieo** [creativecreatorormaybenot/wakelock#208]
It seems like there has been no releases in the last 10 months.

Does anyone know if this package/repository has been abandoned?

**Comment by wujek-srujek** [comment]
According to comments in other issues, the author hasn't been available in the last months, and this will continue in the next months as well. There is a proposal for Fluttercommunity to take over / fork this plugin, see https://github.com/fluttercommunity/community/issues/123, but that one also hasn't had any activity for 2 weeks (I'm not counting '+1's here).
This forced me to create my own fork with the necessary changes (update to win32-v5 and the 'namespace' change for Android). I also hope it will get resolved soon.

**Comment by jamesncl** [comment]
[wakelock_plus](https://pub.dev/packages/wakelock_plus) is now on pub.dev, maintained by [fluttercommunity.dev](https://pub.dev/publishers/fluttercommunity.dev)

**Comment by creativecreatorormaybenot** [comment]
I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
