### ISSUE TITLE
Feature request: Dim screen (but keep it on)

### ISSUE THREAD

**Issue by GeorgeF0** [creativecreatorormaybenot/wakelock#210]
Hi, I was wondering if it's possible to have a feature that allows to keep the screen on, but allow it to dim.

I think this feature will protect the screen when the activity that requires the screen to remain on takes a long time to complete (such as a 1-hour workout).

In terms of the API, I imagine this can be an optional parameter (that can default to false so as to not change current behavior), perhaps something like:
```
Wakelock.enable(allowDim: true);
Wakelock.disable();
Wakelock.toggle(enable: shouldBeEnabled, allowDim: true); // I guess allowDim won't do anything if shouldBeEnabled is false
```

Samsung's Clock app behaves the same when you start a timer and leave the app in the foreground.

Would this be possible? Thanks!

**Comment by creativecreatorormaybenot** [comment]
I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
