### ISSUE TITLE
Package incompatibility! win32 ^3.0.0

### ISSUE THREAD

**Issue by Sypzer** [creativecreatorormaybenot/wakelock#220]
Considering the fact that the package was published 12 months ago, I suggest updating the dependencies as some packages are incompatible. I wish I could use your package as it is very useful, but I have to change too many other packages in order to use this one and I cannot do that unfortunately.

For me the single dependency in this package that caused problems is win32: ^3.0.0.

**Comment by miracoli** [comment]
@Sypzer 
Consider switching to [https://pub.dev/packages/wakelock_plus](https://pub.dev/packages/wakelock_plus)
Published by fluttercommunity.dev

It is a continuation of this project as the owner is not able to work on it at the moment afaik.

**Comment by creativecreatorormaybenot** [comment]
I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
