### ISSUE TITLE
An ios NSRangeException error may be caused by wakelock

### ISSUE THREAD

**Issue by drawcall** [creativecreatorormaybenot/wakelock#230]
https://github.com/flutter/flutter/issues/126657

Please help check it

**Comment by creativecreatorormaybenot** [comment]
Are you using `wakelock` and still experiencing this issue? The OP of the issue you linked states that the issue has been resolved in newer versions of `wakelock`.

**Comment by JW94** [comment]
When I use the command `flutter pub add wakelock`, it consistently adds an older version (0.4.0) to the `pubspec.yaml` file instead of the latest version. I think this was the reason for the wrong version number.
