### ISSUE TITLE
Address privacy manifest requirement

### ISSUE THREAD

**Issue by wagnerjk** [creativecreatorormaybenot/wakelock#233]
This plugin is listed on https://developer.apple.com/support/third-party-SDK-requirements/ as requiring a privacy manifest. It seems like you need to add a manifest that lists your required reason usage.

See https://github.com/flutter/flutter/issues/131940 and https://github.com/flutter/flutter/issues/131495 for context.

**Comment by creativecreatorormaybenot** [comment]
Hi - I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
