### ISSUE TITLE
PlatformException

### ISSUE THREAD

**Issue by sajib-mridha-nor** [creativecreatorormaybenot/wakelock#238]
facing issuses is 
  PlatformException(channel-error, Unable to establish connection on channel., null, null)

here is my flutter sdk and wakelock version
environment:
sdk: '>=3.0.5 <4.0.0'

wakelock: ^0.4.0

android: minSdkVersion 21

**Comment by creativecreatorormaybenot** [comment]
Hi - I will soon discontinue this repository. Please use [wakelock_plus: ^1.1.6](https://pub.dev/packages/wakelock_plus) instead.
