### ISSUE TITLE
Discontinuation addition

### ISSUE THREAD

**Issue by guyluz11** [creativecreatorormaybenot/wakelock#241]
Please also add the discontinuation in the readme with a link to the new package.

There is also a way to add a label for it in pub.dev, it would be nice if it would also get added.

**Comment by creativecreatorormaybenot** [comment]
Yes that is my plan and definitely very beneficial - I also want to publish a new version to Pub to mention the continuation package `wakelock_plus` in the README. This way, there should be no more ambiguity 👌🏼

**Comment by guyluz11** [comment]
Meany thanks 🙏
