### ISSUE TITLE
Redeclaration: WakelockPlugin Android build exception

### ISSUE THREAD

**Issue by 120011676** [creativecreatorormaybenot/wakelock#28]
wakelock:
    dependency: transitive
    description:
      name: wakelock
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.1.4+1"

Launching lib/main.dart on MI 5 in debug mode...
Running Gradle task 'assembleDebug'...
e: /Users/say/.pub-cache/hosted/pub.flutter-io.cn/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (13, 14): Redeclaration: WakelockPlugin
e: /Users/say/.pub-cache/hosted/pub.flutter-io.cn/wakelock-0.1.4/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (13, 14): Redeclaration: WakelockPlugin
e: /Users/say/.pub-cache/hosted/pub.flutter-io.cn/wakelock-0.1.4/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (37, 14): Unresolved reference: setup

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wakelock:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by 120011676** [comment]
delete 
righit

**Comment by creativecreatorormaybenot** [comment]
You need to run `flutter clean` and then `flutter pub get` again.  
The problem here is that you still have an old version of the plugin cached, which declares classes with the same name.

**Comment by 120011676** [comment]
@creativecreatorormaybenot good
