### ISSUE TITLE
Not a true wakelock

### ISSUE THREAD

**Issue by rlueders** [creativecreatorormaybenot/wakelock#30]
Not a true wake lock as described here: https://developer.android.com/training/scheduling/wakelock

The Android side of this plugin does not implement an actual PowerManger wakelock, rather it implements a FLAG_KEEP_SCREEN_ON.  I was looking for a wakelock plugin, but this plugin appears to be miss-named, or the implementation is incorrect given the current name.

**Comment by creativecreatorormaybenot** [comment]
Thank you for your feedback 🙂

Obviously, both the naming and implementation decisions were made conciously.

I believe that wakelock is the best cross-platform term for keeping the screen awake (this has also always been clearly stated in the plugin description).

Please see #1 (it has been known from the start 😃).  I closed it because there did not seem to be interest or an answer to my question regarding how you would want to do something with it in Flutter without writing native Android code **anyway**. If you have an answer for this, please comment on #1 👍🏽

I hope this answered your concerns.

**Comment by creativecreatorormaybenot** [comment]
Essentially a duplicate of #1, which is why I redirected you to there.

If you think that #1 is not an appropriate place for continuing this discussion, please open a new issue that takes into account both #1 and this issue 🙂 Pull requests are always welcome.

**Comment by rlueders** [comment]
My intent is to use the wakelock to keep the accelerator running in the background.  As such, the Flutter app would not be starting any new events in the background, rather it would continue listening to accelerometer events that were started prior to the screen turning off.  Something like the following:

1: Start accelerometer 
2. Enable wake lock
3. Continually listen to new accelerometer events (screen might or might not turn off during this period depending on user-set timeout value, or user behavior)  Preferable the screen could be turned off to conserve battery. 
4. Disable wake lock
5. Stop accelerometer

**Comment by creativecreatorormaybenot** [comment]
Does the Flutter code run while the screen is turned off? My understanding was that this is not possible currently, which is why I closed #1.

**Comment by rlueders** [comment]
I understand now. If the flutter engine stops running when the screen is turned off, then it doesn't matter if the wake lock is active or not. 

It appears that what I am trying to accomplish is well documented here: https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

However with this approach I will not be able to use the existing sensors plugin from the flutter dev team and it doesn't require a wake lock. 


I agree that this can be closed.

**Comment by icnahom** [comment]
Considering how difficult this subject is, I think it's a big mistake to name it 'wakelock'. I hope something could be done with this issue. It was very misleading for me.
