### ISSUE TITLE
android.permission.WAKE_LOCK

### ISSUE THREAD

**Issue by awhitford** [creativecreatorormaybenot/wakelock#31]
Like [Screen](https://pub.dev/packages/screen#usage), does this package require the `WAKE_LOCK` permission?
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

Shouldn't this be added to the Readme?

**Comment by k3wals** [comment]
Just tested on Android 9 (Pie) and I didn't need to add the permission for the screen to remain on.

**Comment by creativecreatorormaybenot** [comment]
No, it is not required. This is only required for partial wake locks, which the plugin does not use. See #1 ⁦👍🏽⁩
