### ISSUE TITLE
support brightness?

### ISSUE THREAD

**Issue by softmarshmallow** [creativecreatorormaybenot/wakelock#36]
like https://github.com/clovisnicolas/flutter_screen does.

**Comment by creativecreatorormaybenot** [comment]
Thanks for opening this issue! 

This plugin is currently only planned to include screen wakelock functionality.  
So I sadly have to disappoint you with the brightness feature request.

The next feature that will be implemented is #17 🙂

**Comment by softmarshmallow** [comment]
I agree, but i think what developers using this package wants is more functionality related to native screen, not the web support. for the native screen functionality, there could be wake lock, screen brightness, etc.
