### ISSUE TITLE
 MissingPluginException(No implementation found for method toggle on channel wakelock

### ISSUE THREAD

**Issue by andreeapurta** [creativecreatorormaybenot/wakelock#37]
Hi! I get this error in debug console when I use wakelock:

E/flutter (17630): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method toggle on channel wakelock)

Here's my code:

```
import 'package:wakelock/wakelock.dart';
class _MyHomePageState extends State<MyHomePage> {
bool on = true;
// The following statement enables the wakelock.
 void initState() {
    super.initState();
    Wakelock.toggle(on: on);
}
```

Also I do have this added in my AndroidManifest.xml     `<uses-permission android:name="android.permission.WAKE_LOCK" />`
And this in dependencies :   wakelock: ^0.1.4+2

How can I solve this?

**Comment by creativecreatorormaybenot** [comment]
Thank you for reporting this issue 😃

You do not need to add the permission on Android. What version of Flutter are you using?

**Comment by andreeapurta** [comment]
v1.17.4

**Comment by creativecreatorormaybenot** [comment]
@andreeapurta That version seems to be a little outdated. I mean it should still work with that version, but can you reproduce the bug with Flutter v`1.20.3` (latest `stable`)?

You just need to run `flutter upgrade`.

**Comment by andreeapurta** [comment]
Hi! Thank you so much! You are great. I updated flutter and dart and now everything works! Big thanks again for the support!
