### ISSUE TITLE
Module 'wakelock' not found in xcode 11.6

### ISSUE THREAD

**Issue by RaphaelRevivor** [creativecreatorormaybenot/wakelock#39]
Hi,

I am using this futter package on Xcode 11.6 in my app. When trying to debug the app on my iPad, I got:
Module 'wakelock' not found

Anyone knows why and how to solve the issue?

Thanks,
Raphael

**Comment by creativecreatorormaybenot** [comment]
Do you think this could be a duplicate of #34, #35, or #37?

**Comment by RaphaelRevivor** [comment]
Hi @creativecreatorormaybenot , sorry for the delay, I was caught up with other stuffs. I think #34 , #34 , or #37 are not related. 

However, I found this [https://github.com/flutter/flutter/issues/53573](url), which seems to be a similar issue. And it seems the issue is on the macOS/flutter side, and mostly related to the Podfile.

To solve the issue my steps are:
1. open a terminal and go to my_flutter_project/
2. go to my_flutter_project/ios/, delete Podfile, Podfile.lock and Pods/
3. go back to my_flutter_project/ and do: flutter clean
4. fluter build ios

Issue closed.
