### ISSUE TITLE
regression: Plugin project :import_js_library not found.

### ISSUE THREAD

**Issue by llucax** [creativecreatorormaybenot/wakelock#49]
After upgrading to 0.2.0+1 I'm getting this "error" (in quotes because it's shown in red but it doesn't actually prevents it from working) when running `flutter run` in my project:

```
Plugin project :import_js_library not found.
```

**Comment by creativecreatorormaybenot** [comment]
Thanks for reporting the issue 👍

No need to worry about this 🙂 Duplicate of #48.

**Comment by creativecreatorormaybenot** [comment]
Duplicate of #48

**Comment by llucax** [comment]
Woops! Sorry, I usually check if the issue was already reported, I guess I forgot this time :-/
