### ISSUE TITLE
[Feature-Request]: Wakelock for Desktop (Mac, Windows, Linux)

### ISSUE THREAD

**Issue by Ahmadre** [creativecreatorormaybenot/wakelock#57]
At first: Thanks you so much for wakelock and the web support!

I am one of the maintainer of the chewie package and we're using wakelock, but would also like to support desktop plattforms in future.

Is it possible to have wakelock_platform_interface or wakelock for mac, windows and linux?

Thanks in regards.
Rebar :)

**Comment by creativecreatorormaybenot** [comment]
@Ahmadre Thanks so much for using the package and opening the issue 🙏

I already created `wakelock_platform_interface` recently, so adding support should be really easy 👌

Do you have experience with these platforms? I personally do not have experience with Flutter on these platforms, so a contribution would be very helpful in this case.  
If you know the necessary platform calls but you are not sure about the plugin connection, I think that I should also be able to finish it 🙂

**Comment by Ahmadre** [comment]
Very good 👌🏼 then I'll start with Mac support at first :)

**Comment by creativecreatorormaybenot** [comment]
Closing this as #96 added Windows support. I will be releasing it today.

In place of this, I will open an issue for Linux support specifically :)
