### ISSUE TITLE
The plugin `wakelock` requires your app to be migrated to the Android embedding v2

### ISSUE THREAD

**Issue by Fabio-Paccosi** [creativecreatorormaybenot/wakelock#67]
Hello guys, 

When I run flutter pub get, from today, I've got this message:

The plugin `wakelock` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

In another project created at the same time, I've got the same pubspec.yaml file but I can run flutter pub get correctly.

This is my pubspec.yaml file:

`name: app_inteface_pwa
description: A Flutter project.

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^5.4.1
  shimmer: ^1.0.1
  cupertino_icons: ^1.0.0
  flutter_login: ^1.0.14
  string_validator: ^0.1.4
  shared_preferences: "^0.5.8"
  json_serializable: ^3.3.0
  firebase_messaging: ^5.1.4
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.1+6
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^2.5.1
  flutter_inapp_purchase: ^2.3.2
  in_app_purchase: 0.3.4+15
  network_to_file_image: ^2.3.1
  path_provider: ^1.6.11
  connectivity: '>=0.4.9 <2.0.0'
  datetime_picker_formfield: ^1.0.0
  crypto: ^2.1.4
  basic_utils: ^2.6.0
  flutter_spinkit: "^4.1.2"
  flutter_offline: "^0.3.0"
  async_loader: ^0.1.2
  carousel_slider: ^2.3.1
  flutter_statusbarcolor: ^0.2.3
  webview_flutter: ^1.0.6
  flutter_inappwebview: ^4.0.0+4
  styled_text: ^1.0.2+1  
  flutter_downloader: ^1.5.2
  permission_handler: ^5.0.1+1
  package_info: '>=0.4.3+2 <2.0.0'
  flutter_html: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  assets:
     - assets/_default/

  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Roboto/Roboto-Light.ttf
            weight: 200
          - asset: assets/fonts/Roboto/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto/Roboto-Regular.ttf
            weight: 300
          - asset: assets/fonts/Roboto/Roboto-Bold.ttf
            weight: 700
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
            weight: 100
          - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
            weight: 100
            style: italic
          - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
            weight: 400
          - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
            weight: 400
            style: italic
          - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
            weight: 800
            style: italic
          
`

**Comment by creativecreatorormaybenot** [comment]
Hi @Fabio-Paccosi 🙂 

Thanks for using the plugin - this is most likely not an issue with wakelock.

Can you follow the steps at https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects?

**Comment by paccosi93** [comment]
> Hi @Fabio-Paccosi 🙂
> 
> Thanks for using the plugin - this is most likely not an issue with wakelock.
> 
> Can you follow the steps at https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects?

I've tried to follow this guide, but my application is currently use mainactivity.kt and this guide is not clear enought for my case...

**Comment by creativecreatorormaybenot** [comment]
@paccosi93 You can always delete the `android` directory in your app and run `flutter create .` again.

**Comment by creativecreatorormaybenot** [comment]
Or compare to a newly generated version - anyway, this is not an issue with wakelock in that case but rather with https://github.com/flutter/flutter.
