### ISSUE TITLE
pub get error

### ISSUE THREAD

**Issue by NaarGes** [creativecreatorormaybenot/wakelock#69]
Hi
Im getting this error while trying to add wakelock ^0.2.1+1 into my pubspec.yaml 

Because every version of flutter_test from sdk depends on meta 1.1.8 and wakelock >=0.2.0 <0.3.0-nullsafety.0 depends on meta ^1.2.0, flutter_test from sdk is incompatible with wakelock >=0.2.0 <0.3.0-nullsafety.0.

and when I comment out flutter_test, I also get this error:

Because every version of flutter from sdk depends on meta 1.1.8 and wakelock >=0.2.0 <0.3.0-nullsafety.0 depends on meta ^1.2.0, flutter from sdk is incompatible with wakelock >=0.2.0 <0.3.0-nullsafety.0.

**Comment by creativecreatorormaybenot** [comment]
Thanks for opening the issue!

It seems that Flutter is using an older version of `meta`.

What version / channel of Flutter are you using? :)

---

I think that I can downgrade to an older version anyway, however 🤔

**Comment by NaarGes** [comment]
thank you for the hint
I wasn't using latest flutter version
I upgrade flutter and now everything works fine
