### ISSUE TITLE
Wakelock is not ARMV7

### ISSUE THREAD

**Issue by jcairo** [creativecreatorormaybenot/wakelock#8]
When building ios for release (flutter build ios) I receive a message 'wakelock.framework/wakelock is not armv7'

Is there an easy fix for this?

**Comment by creativecreatorormaybenot** [comment]
I am not sure if this is an issue with the `wakelock` plugin. You might want to take a look and read through https://github.com/flutter/flutter/issues/2089 or do you know about a potential source for this issue in the plugin?

**Comment by jcairo** [comment]
Apologies, this does not appear to be a problem with wakelock after all.
