### ISSUE TITLE
FCMService: Invalid notification content

### ISSUE THREAD

**Issue by benyamin218118** [creativecreatorormaybenot/wakelock#91]
i am getting this error about FCM after importing wakelock library in my flutter project:
```
D/FCMService: FCM received
D/FCMService: Invalid notification content
```
but if i remove the wakelock plugin from my dependencies list , it works well as it was working before!
what's wrong?

**Comment by creativecreatorormaybenot** [comment]
I doubt that this is related (I do not see any reason why it would be).

Can you try to upgrade Flutter and use `flutter clean`?  
Also what platform are you running on?

**Comment by benyamin218118** [comment]
im running on android 10 (samsung A6+) , i tried flutter clean , my flutter version is `Flutter 1.22.5 • channel stable` .
i will try to update my flutter and let you know if it fixed. thanks for answering

**Comment by creativecreatorormaybenot** [comment]
@benyamin218118 Do you have any idea why this might be happening looking at the Android code?

We use FCM as well and I do not think we are having any issues with `wakelock` 🤔

**Comment by benyamin218118** [comment]
not really ..
i have upgraded my flutter in its stable channel
but still so :
 ```
D/FCMService(15084): FCM received
D/FCMService(15084): Invalid notification content
```

may there is a little conflict between this and one of my other dependencies, i have no idea :/

**Comment by creativecreatorormaybenot** [comment]
If you take a look at the Android code: https://github.com/creativecreatorormaybenot/wakelock/blob/master/wakelock/android/src/main/kotlin/creativemaybeno/wakelock/WakelockPlugin.kt

It seems pretty unlikely that it conflicts with notifications 🤔

**Comment by benyamin218118** [comment]
exactly , i dont really know where is the problem
should i close the issue because this maybe not related to wakelock?

**Comment by creativecreatorormaybenot** [comment]
@benyamin218118 You can decide that. We can leave it open if you want to.

I have no idea how to solve this on my end right now, maybe we'll get more insights later.

I would suggest opening an issue for the FCM plugin.

**Comment by benyamin218118** [comment]
ok
tnx for your time♥.
