### ISSUE TITLE
`wakelock` doesn't have a main class defined

### ISSUE THREAD

**Issue by MarkStraub** [creativecreatorormaybenot/wakelock#92]
The plugin `wakelock` doesn't have a main class defined in
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.2.1+1\android\src\main\java\creativemaybeno\wakelock\WakelockPlugin.java or
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.2.1+1\android\src\main\kotlin\creativemaybeno\wakelock\WakelockPlugin.kt. This is likely to due to an incorrect `androidPackage: 
creativemaybeno.wakelock` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider  
using a different plugin in the meanwhile.

Flutter doctor:
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale de-CH)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\TERMINAL\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

**Comment by creativecreatorormaybenot** [comment]
Hi :) Thanks for opening the issue 🙂

I think this issue is likely fixed by running `flutter clean` and then building again - can you try that?  
I am pretty confident that the plugin is properly configured.

**Comment by MarkStraub** [comment]
Thanks for your fast answer. =)

Unfortunatelly `flutter clean` does'nt help. I also tried a reboot with no result.

**Comment by creativecreatorormaybenot** [comment]
@MarkStraub The file clearly exists, however: https://github.com/creativecreatorormaybenot/wakelock/blob/afd369e24d949edcaf45ef980a45d423dfb5750a/wakelock/android/src/main/kotlin/creativemaybeno/wakelock/WakelockPlugin.kt

There has to be something wrong with your locally cached version of the plugin 🤔

**Comment by MarkStraub** [comment]
It seems really strange. Hopefully I will get it running.

Thanks anyway :-)

**Comment by MarkStraub** [comment]
If I take the older Version 0.2.1 `wakelock: 0.2.1`it works fine.

Was there a big change between 0.2.1 and 0.2.1+1?
