### ISSUE TITLE
can the wake lock be overruled by the user? 

### ISSUE THREAD

**Issue by Jossnaz** [creativecreatorormaybenot/wakelock#93]
just asking - for example if I play mp3s using my phone, is that a wake lock as well as the screen does turn off, but the music continues playing.

e.g. can the wake lock be overruled by the user if he presses the screen lock button? or will the app keep running?

what about battery life? subjective rule of thumb thoughts?

**Comment by creativecreatorormaybenot** [comment]
Hi @Jossnaz, thanks for opening the issue :)

This plugin **only** prevents the device from automatically turning off the screen. It has nothing to do with partial wakelocks in the background / CPU wakelocks.  
Therefore, it has no impact on the user manually turning off the phone screen :) (this plugin does not do anything in the background)
